Type = "v8"
Intro = ""
Desc = "Mud红尘的机器人脚本"
OnOpen = "onOpen"
OnClose = "onClose"
OnConnect = "onConnected"
OnDisconnect = "onDisconnected"
OnBroadcast = "onBroadcast"
OnFocus = ""
OnLoseFocus = ""
OnKeyUp = "onKeyup"
OnHUDClick = ""
OnResponse = "onResponse"
OnAssist = "onAssist"
OnBuffer = ""
OnSubneg = ""
OnBufferMin = 0
OnBufferMax = 0
Channel = ""
Timers = []
RequiredParams = []

[[Triggers]]
  ID = "d1fu8bc9ec0l0d71gvntjv"
  Name = "core.line"
  Enabled = true
  Match = "*"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.LineEvent('line')"
  SendTo = 0
  Sequence = 99
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = false
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = ""
  IgnoreCase = false
  KeepEvaluating = true
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""

[[Triggers]]
  ID = "d1h4353vpnum6r733tr6jt"
  Name = "core.hpstart"
  Enabled = true
  Match = "你目前的状态属性如下："
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.LineEvent('core.hp')"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = "event"
  IgnoreCase = false
  KeepEvaluating = true
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""

[[Triggers]]
  ID = "d1h4362qfke8e5733tr7ii"
  Name = "core.hpm"
  Enabled = true
  Match = "你目前的属性上限如下："
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.LineEvent('core.hpm')"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = "event"
  IgnoreCase = false
  KeepEvaluating = true
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""

[[Triggers]]
  ID = "d1h436g825u6h1733tr7vr"
  Name = "core.special"
  Enabled = true
  Match = "你现在会以下这些特技："
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.LineEvent('core.special')"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = "event"
  IgnoreCase = false
  KeepEvaluating = true
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""

[[Triggers]]
  ID = "d1h43815675a95733trbkr"
  Name = "core.score"
  Enabled = true
  Match = "你的状态属性如下："
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.LineEvent('core.score')"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = "event"
  IgnoreCase = false
  KeepEvaluating = true
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""

[[Triggers]]
  ID = "d1h44rh3tfqpn9733trdfc"
  Name = "core.chaforce"
  Enabled = true
  Match = "你目前所学到的基本内功及相关技能"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.LineEvent('core.chaforce')"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = false
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = "event"
  IgnoreCase = false
  KeepEvaluating = true
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""

[[Triggers]]
  ID = "d1h44rs7h1p5r9733trdrj"
  Name = "core.skills"
  Enabled = true
  Match = "你目前所学到的所有技能"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.LineEvent('core.skills')"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = false
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = "event"
  IgnoreCase = false
  KeepEvaluating = true
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""

[[Triggers]]
  ID = "d1h45455bdeji6733trk08"
  Name = "core.jifa"
  Enabled = true
  Match = "以下是你目前使用中的特殊技能。"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.LineEvent('core.jifa')"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = false
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = ""
  IgnoreCase = false
  KeepEvaluating = true
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""

[[Triggers]]
  ID = "d1h454pog5vvug733trn01"
  Name = "core.nojifa"
  Enabled = true
  Match = "你现在没有使用任何特殊技能。"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.LineEvent('core.nojifa')"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = false
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = ""
  IgnoreCase = false
  KeepEvaluating = true
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""

[[Triggers]]
  ID = "d1h454s4ahbgrv733trnj8"
  Name = "core.noskill"
  Enabled = true
  Match = "你目前并没有学会任何技能。"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.LineEvent('core.noskill')"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = false
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = ""
  IgnoreCase = false
  KeepEvaluating = true
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""

[[Triggers]]
  ID = "d1h4577j4c9d84733ts3vi"
  Name = "core.skillimproved"
  Enabled = false
  Match = "^你的.+进步了！$"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.LineEvent('core.noskill')"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = "event"
  IgnoreCase = false
  KeepEvaluating = true
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""

[[Triggers]]
  ID = "d1h457c64377e7733ts441"
  Name = "core.bug"
  Enabled = true
  Match = "^你在\\S+中的错误报告积累点数为(\\d+)点。$"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.LineEvent('core.bug')"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = "event"
  IgnoreCase = false
  KeepEvaluating = true
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""

[[Triggers]]
  ID = "d1h457jj3ia2b9733ts4ns"
  Name = "core.bug0"
  Enabled = true
  Match = "^你在\\S+中尚无报告过任何错误。$"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.LineEvent('core.bug0')"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = "event"
  IgnoreCase = false
  KeepEvaluating = true
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""

[[Triggers]]
  ID = "d1h458eooe238g733tsc73"
  Name = "App.Core.Room.OnName"
  Enabled = true
  Match = "^[^，。！：.『』【】…“”？?>.]{2,10}$"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.FilterLineEvent(\"core.normalroomname\",\"core.roomname\")"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = ""
  IgnoreCase = false
  KeepEvaluating = true
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""

[[Triggers]]
  ID = "d1h458iloej23b733tsd4n"
  Name = "core.exit"
  Enabled = true
  Match = "^    这里(唯一的出口是|明显的出口是|没有任何明显的出路)(.*)"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.LineEvent(\"core.onexit\")"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = ""
  IgnoreCase = false
  KeepEvaluating = true
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""

[[Aliases]]
  ID = "d1fv62osn8i7nf726vpqu6"
  Name = "queue"
  Enabled = true
  Match = "#(to|wait|do|loop|nobusy|sync|search|killin|prepare|kill|wpon|wpoff|unwield|buy|study|jifa)((\\s|\\|\\|).*)?$"
  Send = ""
  Script = "App.UserQueue.OnAlias"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Group = ""
  IgnoreCase = false
  KeepEvaluating = false
  Menu = false
  OmitFromLog = false
  Variable = ""
  ReverseSpeedwalk = false
  OmitFromOutput = false
  OmitFromCommandHistory = false

[[Aliases]]
  ID = "d1fv6bbo0pupo8726vq611"
  Name = "App.Alias.Stop"
  Enabled = true
  Match = "#stop"
  Send = ""
  Script = "App.Alias.Stop"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = false
  Group = ""
  IgnoreCase = false
  KeepEvaluating = false
  Menu = false
  OmitFromLog = false
  Variable = ""
  ReverseSpeedwalk = false
  OmitFromOutput = false
  OmitFromCommandHistory = false

[[Aliases]]
  ID = "d1fvd8m57s7g4i72l2d67r"
  Name = "App.Core.Quest.OnAlias"
  Enabled = true
  Match = "#start(\\s*.+)?$"
  Send = ""
  Script = "App.Core.Quest.OnAlias"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Group = ""
  IgnoreCase = false
  KeepEvaluating = false
  Menu = false
  OmitFromLog = false
  Variable = ""
  ReverseSpeedwalk = false
  OmitFromOutput = false
  OmitFromCommandHistory = false

[[Aliases]]
  ID = "d1g0itgqb020ob72ii59ar"
  Name = "start"
  Enabled = true
  Match = "start"
  Send = "#start"
  Script = ""
  SendTo = 10
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = false
  Group = ""
  IgnoreCase = false
  KeepEvaluating = false
  Menu = false
  OmitFromLog = false
  Variable = ""
  ReverseSpeedwalk = false
  OmitFromOutput = false
  OmitFromCommandHistory = false

[[Aliases]]
  ID = "d1g0ithkt1a40a72ii59as"
  Name = "stop"
  Enabled = true
  Match = "spqt"
  Send = "#stop"
  Script = ""
  SendTo = 10
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = false
  Group = ""
  IgnoreCase = false
  KeepEvaluating = false
  Menu = false
  OmitFromLog = false
  Variable = ""
  ReverseSpeedwalk = false
  OmitFromOutput = false
  OmitFromCommandHistory = false
